language: ruby

services:
  - postgresql

script:
  - export RAILS_ENV=test
  - bundle exec rake db:create db:schema:load db:test:prepare
  - bundle exec spring binstub --all
  - bundle install
  - bundle exec rspec

rvm:
  - 2.3.1

deploy:
  provider: heroku
  api_key: HEROKU_API_KEY
  app:
    master: guimifiu
    staging: staging-guimifiu

notifications:
      slack: tccjoaomarco:2hqlJdioZoVlvpFInYZVBqqS
