language: ruby

services:
  - postgresql

script:
  - ./scripts/complexity_check.sh
  - export RAILS_ENV=test
  - bundle exec rake db:create db:schema:load db:test:prepare
  - bundle exec spring binstub --all
  - bundle install
  - bundle exec rspec

rvm:
  - 2.3.1
notifications:
  email:
    recipients:
      - marcowilliamdf@gmail.com
  
branches:
  only:
    - master

notifications:
      slack: tccjoaomarco:2hqlJdioZoVlvpFInYZVBqqS
